name: iOS-POC-MVVM
options:
  bundleIdPrefix: com.poc
  deploymentTarget:
    iOS: "15.0"
  createIntermediateGroups: true
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
targets:
  iOS-POC-MVVM:
    type: application
    platform: iOS
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.poc.iOS-POC-MVVM
        INFOPLIST_FILE: Sources/App/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        CLANG_ENABLE_OBJC_ARC: YES
        TARGETED_DEVICE_FAMILY: "1"
        IPHONEOS_DEPLOYMENT_TARGET: "15.0"
        SWIFT_OBJC_BRIDGING_HEADER: Sources/iOS-POC-MVVM-Bridging-Header.h
        SWIFT_VERSION: "5.0"
